language: android
android:
  components:
    - build-tools-28
    - build-tools-27.0.3
    - android-28
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-googletv-license-.+'


before_install:
- yes | sdkmanager "platforms;android-28"






